artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/izam-mohammed/data-source/raw/main/sentiment_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/sentiment_data/train.txt
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/sentiment_data/train.txt
  text_corpus_name: text_corpus.csv
  target_col_encoded_file: target_col_encoded_df.csv
  vectorizer_name: tfidf_vectorizer.pkl
  vocabulary_name: vocabulary.pkl
  test_size: 0.1

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl
  vectorizer_path: artifacts/data_transformation/tfidf_vectorizer.pkl
  vocabulary_path: artifacts/data_transformation/vocabulary.pkl